### ISSUE TITLE
Problems in the Concepts

### ISSUE THREAD

**Issue by LinguList** [lexibank/baf2#10]
@IndianaTones, could you please check our discussion about the concepts here: https://github.com/concepticon/concepticon-data/pull/1293

We'd need you to answer a few questions and help us to correct the erroneous glosses and mappings there :)

**Comment by LinguList** [comment]
We have quite a few errors now, where the LEXIBANK_GLOSS is missing:

```
THORN                                                                                                                                                                
WAGES
SPRING OR WELL
TEN
```

Can I ask you to check with older versions of the list for the [original concepts in our concept list]() and add them in LEXIBANK_GLOSS? You can run with the cldf conversion to see if no of the errors is appearing.

**Comment by LinguList** [comment]
Here is the link, where you find the original gloss as it is in the data: https://github.com/lexibank/baf2/commit/499cee5748bf11137784268b04a5387b05e0f2b6

**Comment by LinguList** [comment]
So you search for the row in which THORN was changed and add THORN as LEXIBANK_GLOSS there, @IndianaTones

**Comment by IndianaTones** [comment]
Ah, so I have to add those ones as well. Ok, lemme try to track the errors on my end.

**Comment by LinguList** [comment]
Yes, there were more, I already added them, then decided to not do this one by one but rather write a script that points to problems here.

**Comment by LinguList** [comment]
So the CLDF now checks explicitly for the problems.

**Comment by IndianaTones** [comment]
--concepticon-version=v2.5.0 ?

**Comment by LinguList** [comment]
you need concepticon verison 3.0, you should update that part in your 
data, identify the concepticon-data folder, go there, and do git pull

**Comment by IndianaTones** [comment]
got it. and which lexibank is it? not hantbang as that isn't working or am I off?

**Comment by LinguList** [comment]
cldfbench lexibank.makecldf lexibank_hantbang.py 
--glottolog-version=v4.7 --concepticon-version=v3.0.0 --clts-version=v2.2.0

**Comment by IndianaTones** [comment]
yeah, it keeps telling me I don't exist 

Invalid dataset spec: <lexibank.dataset> lexibank_hantbang.py

**Comment by LinguList** [comment]
lexibank_baf2, I mean: we work in the folder baf2, we have the script 
lexibank_baf2.py there, right? So it must be lexibank_baf2.py or simply 
baf2 if you have made a pip install -e . in the folder

**Comment by IndianaTones** [comment]
alright for baf2, still doing something wrong though - pls check most recent version of concepts.tsv

**Comment by LinguList** [comment]
Why would you think you are doing something wrong?

**Comment by IndianaTones** [comment]
errors = 

INFO    running _cmd_makecldf on baf2 ...
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by LinguList** [comment]
@IndianaTones, please, having worked for years with Python now, you should know that it does not help me to give me some snippet of the error message, I really need to know also what command you feed it, I cannot guess this from the erroneous output.

**Comment by IndianaTones** [comment]
I ran the command as suggested above (repeated here but I omit my paths to repo folders):

`$ cldfbench lexibank.makecldf lexibank_baf2.py --glottolog-version=v4.7 --concepticon-version=v3.0.0 --clts-version=v2.2.0`

**Comment by LinguList** [comment]
Okay, sorry, I have a very high number of requests at the same time, so I usually do not find time to re-read each thread.

**Comment by LinguList** [comment]
But the error code you give me still deprives me of seeing the essential core: where in the script is this error thrown?

**Comment by LinguList** [comment]
So I need the full error line, otherwise, I cannot tell anything.

**Comment by IndianaTones** [comment]
yes my apologies on that one, always hesitant to add in my paths - sorry for making things complicated

Traceback (most recent call last):
  File "/Users/linguist/Documents/GitHub/baf2/venv/bin/cldfbench", line 8, in <module>
    sys.exit(main())
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/cldfbench/__main__.py", line 89, in main
    return args.main(args) or 0
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/pylexibank/commands/makecldf.py", line 24, in run
    with_dataset(args, 'makecldf', dataset=dataset)
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/cldfbench/cli_util.py", line 161, in with_dataset
    res = func(*arg, args)
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/pylexibank/dataset.py", line 218, in _cmd_makecldf
    super()._cmd_makecldf(args)
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/cldfbench/dataset.py", line 206, in _cmd_makecldf
    self.cmd_makecldf(args)
  File "/Users/linguist/Documents/GitHub/baf2/./lexibank_baf2.py", line 76, in cmd_makecldf
    if concept["LEXIBANK_GLOSS"].strip():
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by LinguList** [comment]
Yes, you realize that the CSV in etc/concepts.tsv, which you produced, is flagged by GitHub? You have empty cells there, resulting from missing Tab-stops. So the Lexibank_GLOSS is interpreted as None here, but it should be an empty string. So you need to add the tabstops, even if there is nothing else. It is pretty useful to check that GitHub is rendering CSV/TSV files nicely ;)

**Comment by IndianaTones** [comment]
ah ok, I suspected the empty cells in the LEXIBANK_GLOSS column were wreaking havoc. Ok, thank you for this insight! I would not have understood this from the errors though

**Comment by IndianaTones** [comment]
also, not sure how to fix this - on my end, I can see the tab stops where there are empty cells, also in the CONCEPTICON_ID column for where there was no concept - should these be non-empty?

**Comment by LinguList** [comment]
If GitHub complains, you are missing at least one cell with values, or have too much. So this IS an error in the data, if you check this. You can fix by opening a google sheet, copy-pasting the content from github there, and re-copy-pasting it into github. Quite easy hack in fact.

**Comment by IndianaTones** [comment]
Yeah, weird, I had done that, but I did it again, and now it works, but I do have one additional error that had occurred earlier as well:

Traceback (most recent call last):
  File "/Users/linguist/Documents/GitHub/baf2/venv/bin/cldfbench", line 8, in <module>
    sys.exit(main())
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/cldfbench/__main__.py", line 89, in main
    return args.main(args) or 0
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/pylexibank/commands/makecldf.py", line 24, in run
    with_dataset(args, 'makecldf', dataset=dataset)
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/cldfbench/cli_util.py", line 161, in with_dataset
    res = func(*arg, args)
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/pylexibank/dataset.py", line 218, in _cmd_makecldf
    super()._cmd_makecldf(args)
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/cldfbench/dataset.py", line 206, in _cmd_makecldf
    self.cmd_makecldf(args)
  File "/Users/linguist/Documents/GitHub/baf2/./lexibank_baf2.py", line 81, in cmd_makecldf
    args.writer.add_language(**language)
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/pylexibank/cldf.py", line 279, in add_language
    and kw['Glottocode'] in self.args.glottolog.api.cached_languoids:
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/clldutils/misc.py", line 241, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/cldfbench/catalogs.py", line 30, in cached_languoids
    return {lang.id: lang for lang in self.languoids()}
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/cldfbench/catalogs.py", line 24, in languoids
    self.__languoids = list(super().languoids())
  File "/Users/linguist/Documents/GitHub/baf2/venv/lib/python3.10/site-packages/pyglottolog/api.py", line 267, in languoids
    or ((not is_max_level_int) and lang.level <= maxlevel):
TypeError: '<=' not supported between instances of 'NoneType' and 'LanguoidLevel'

**Comment by LinguList** [comment]
Please use the cmd with keyword `--dev`. This will not use glottolog, and the bug is from there. I suppose you have a problematic glottolog version. I suggest to re-install and download the new glottolog from github.com/glottolog/glottolog, so you are sure you have the most recent, updodate version etc.

**Comment by IndianaTones** [comment]
Ok finally!  Just one lexeme appears now - PICK. I added GATHER there as that was what was there before the change so not sure why that is still an issue.

**Comment by LinguList** [comment]
Does GATHER really appear in `raw/bangime-edited.tsv`? If not, can you please check if there is an extended or slightly different gloss for it?

**Comment by IndianaTones** [comment]
No more errors!
