### ISSUE TITLE
Release data for submission

### ISSUE THREAD

**Issue by LinguList** [lexibank/baf2#5]
We should release data with Zenodo.

**Comment by IndianaTones** [comment]
Let me know what I can do and also if it would be feasible to add to Lexibank (re issue no. [3](https://github.com/lexibank/baf2/issues/3))?

**Comment by LinguList** [comment]
Yep, I'll keep you updated, but I think I can make the first release now with all we have, provided the ortho-problems and cogids are fixed.

**Comment by IndianaTones** [comment]
I think everything should be fixed in Edictor at least save for this issue [3](https://github.com/lexibank/baf2/issues/6).
