### ISSUE TITLE
COGIDs linked to multiple entries

### ISSUE THREAD

**Issue by IndianaTones** [lexibank/baf2#6]
I finished going through and correcting the missing COGIDs but then realized that some are linked to more than one entry. For instance:

| DOCULECT | Concept | Value | COGIDS
| ------------- |:-------------:| -----:| -----:|
| Bangime | ANCESTORS | `kāàⁿ` | 27⁴ |
| Bunoge | AGE | `kɛ̀mnɔ̀ kánì` | 26³ 27⁴ |
| Mombo | AGE | `ká:nú kánì` | 26³ 27⁴ |
| Penange | AGE | `ká:mnɔ́ kán` | 26³ 27⁴ |

Seems this is not by accident but should I should fix it by adding in 0 or randomly generated numbers for the Bangime forms especially?

**Comment by LinguList** [comment]
WARNING 8725: TOE             | DogulDom             | 4385 4383 4899 | n ¹/aː + ɡ + s ⁵¹/a j + ɡ
WARNING 9617: YELLOW          | Fulfulde             | 4800       | oː l + o l

**Comment by LinguList** [comment]
These are still erroneous.

**Comment by IndianaTones** [comment]
> These are still erroneous.

fixed. but note my issue above?

**Comment by LinguList** [comment]
OI thought I had answered on that already: you should fix it. It was an accident from manual annotation, I assume, as the automated approach would not merge across concepts.
