### ISSUE TITLE
Please add MORPHEMES column to Edictor

### ISSUE THREAD

**Issue by IndianaTones** [lexibank/baf2#8]
Could you please add a (permanent) MORPHEMES column to our [Edictor Dataset](http://digling.org/edictor/?remote_dbase=bangime&file=bangime&basics=DOCULECT|CONCEPT|TOKENS|COGID|COGIDS|COGID|BORID|NOTE&columns=DOCULECT|CONCEPT|CONCEPT_FRENCH|FAMILY|SUBGROUP|VALUE|FORM|TOKENS|COGID|COGIDS|BORID|STRATUM&split_on_tones=false&async=true&formatter=BORID#glosses_anchor)  so that I can begin adding partial cognates there for noun classes among the Dogon languages? This will be very interesting.

**Comment by LinguList** [comment]
Sorry, only saw this issue now.

**Comment by LinguList** [comment]
Adding columns is actually a no-brainer, but you need to adjust the URL you use to open edictor to SEE them.

**Comment by LinguList** [comment]
So if you use this URL (copy and paste it directly from here into the browser), you see all morphemes as a column:

```
https://digling.org/edictor/?remote_dbase=bangime&file=bangime&columns=DOCULECT|SUBGROUP|FAMILY|CONCEPT|FRENCH|VALUE|FORM|TOKENS|MORPHEMES|COGID|BORID|COGIDS|ALIGNMENT|COMMENT&basics=DOCULECT|CONCEPT|VALUE|FORM|TOKENS|MORPHEMES|COGID|BORID|COGIDS
```

**Comment by IndianaTones** [comment]
Got it - I wonder if I should re-run the code to see how it does with partial morphemes, or do this only on the new dataset?

**Comment by LinguList** [comment]
The code takes full cognates, no partial cognates. Have you drastically modified the data?

**Comment by IndianaTones** [comment]
I have modified the ID's yeah...

**Comment by LinguList** [comment]
This means we have to re-run the code and write a short update for ORE. This does not need to be long, just make sure numbers match, etc., and indicate that the underlying data is now in a new zenodo version, which we'd fix then.

**Comment by IndianaTones** [comment]
If you think it's worth it at this point? If not, can also be done on the new dataset (LanguageIslands).

**Comment by LinguList** [comment]
This depends on what you want to do. ORE offers to make a revision whenever you want. But if we consider this as closed, I'd say: no more modifications here.

**Comment by IndianaTones** [comment]
Yeah, I think we can close this one and focus on the new one. I had wondered about doing this some time ago; seems like it's best to work on the new dataset now though I think.

**Comment by LinguList** [comment]
That is perfectly fine, and more consistent. We can alter easily compared with this dataset.
