### ISSUE TITLE
Release new data that quotes the published study

### ISSUE THREAD

**Issue by LinguList** [lexibank/baf2#9]
We need to publish Version 1.0, which links to the Hantgan et al. study on ORE.

**Comment by mathildavz** [comment]
I'm currently working on adding the word list to Concepticon. I noticed that the sources.bib doesn't include an author name or a title yet. Can this be updated, or should I use the preprint as a source? @LinguList

**Comment by LinguList** [comment]
Ah, my bad, we need to update this.

**Comment by LinguList** [comment]
Here's the source you should quote:

```
@article{Hantgan2022,
    author = {Hantgan, Abbie and Babiker, Hiba and List, Johann-Mattis},
    doi = {https://doi.org/10.12688/openreseurope.14339.2},
    journal = {Open Research Europe},
    number = {10},
    pages = {1-27},
    title = {First steps towards the detection of contact layers in Bangime: A multi-disciplinary, computer-assisted approach [version 2; peer review: 2 approved]},
    volume = {2},
    year = {2022}
}
```

**Comment by mathildavz** [comment]
Great, thank you for your quick reply! @LinguList
